name: Selenium Tests

on:
  push:
    branches: [ UNIEVENTOS-FRONT, UnieventosBackend ]

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Selenium dependencies
        working-directory: e2e-tests
        run: pip install -r requirements.txt

      - name: Run Selenium Tests
        working-directory: e2e-tests
        run: python test_unieventos.py
